// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdztddrfwrmvnnvhbzyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkenRkZHJmd3Jtdm5udmhienl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5MjMxNDksImV4cCI6MjA0OTQ5OTE0OX0.4bJA0fw0U7C0LltcWfTJCFW-_rL_fZSbpU5AbB5yThg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);